name: Build Latest

on:
  push:
    branches: 
      - '*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  appimage:
    name: Build/Test/Upload latest
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    strategy:
      matrix:
        include:
          - container: ghcr.io/seanavery/viam-cpp-base:0.0.2
            TARGET: jetson
            META_PATH: meta.json
          - container: ghcr.io/seanavery/viam-cpp-base-pi:0.0.2
            TARGET: pi
            META_PATH: meta-pi.json
    container:
      image: ${{ matrix.container }}
      options: --platform linux/arm64

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "TARGET=${{ matrix.TARGET }}" >> $GITHUB_ENV
          echo "META_PATH=${{ matrix.META_PATH }}" >> $GITHUB_ENV

      - name: Clean build artifacts
        run: make clean

      - name: Install module dependencies
        run: make dep

      - name: Build viam-csi binary
        run: make build

      - name: Build viam-csi appimage
        run: make package

      - name: Copy binary and appimage to bin folder
        run: make bin

      - name: Run appimage in fresh instance
        run: |
          make image-test
          make test-package

      - name: Authorize GCP upload
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy Files
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          headers: "cache-control: no-cache"
          path: 'bin'
          destination: 'packages.viam.com/apps/csi-camera/${{ env.TARGET }}'
          glob: '*aarch64*'
          parent: false
          gzip: false

      - name: Get latest release version
        id: get_version
        run: |
          apt install -y jq
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "LATEST_RELEASE_VERSION=$LATEST_RELEASE" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing module env variables
        run: |
          echo "TARGET=${{ env.TARGET }}"
          echo "META_PATH=${{ env.META_PATH }}"
          echo "COMMIT_COUNT=${{ env.COMMIT_COUNT }}"
          echo "LATEST_RELEASE_VERSION=${{ env.LATEST_RELEASE_VERSION }}"
          echo "version: ${{ env.LATEST_RELEASE_VERSION }}-${{ github.ref_name }}.${{ env.COMMIT_COUNT }}"

      - name: Update module registry
        uses: viamrobotics/upload-module@main
        if: github.event_name == 'push'
        with:
          meta-path: ${{ env.META_PATH }}
          module-path: module.tar.gz
          platform: linux/arm64
          version: ${{ env.LATEST_RELEASE_VERSION }}-${{ github.ref_name }}.${{ github.run_number }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}

# echo "GITHUB_REF=${{ github.ref }}"
# echo "GITHUB_REF_NAME=${{ github.ref_name }}"
# echo "GITHUB_REF_SLUG=${{ github.ref_slug }}"
# echo "GITHUB_REF_TYPE=${{ github.ref_type }}"
# echo "GITHUB_REPOSITORY=${{ github.repository }}"
# echo "GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}"
# echo "GITHUB_RUN_ID=${{ github.run_id }}"
# echo "GITHUB_RUN_NUMBER=${{ github.run_number }}"
# echo "GITHUB_RUN_AT=${{ github.run_at }}"
# echo "GITHUB_ACTOR=${{ github.actor }}"
# echo "GITHUB_WORKFLOW=${{ github.workflow }}"
# echo "GITHUB_HEAD_REF=${{ github.head_ref }}"
# echo "GITHUB_BASE_REF=${{ github.base_ref }}"
# echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
# echo "GITHUB_EVENT_PATH=${{ github.event_path }}"
# echo "GITHUB_WORKSPACE=${{ github.workspace }}"
# echo "GITHUB_SHA=${{ github.sha }}"