name: Test pull request

on:
  pull_request:
    branches:
      - '*'

jobs:
  test-package:
    runs-on: [buildjet-2vcpu-ubuntu-2204-arm]
    container:
      image: ghcr.io/seanavery/viam-cpp-base:0.0.2
      options: --platform linux/arm64
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Clean build artifacts
      run: make clean

    - name: Install module dependencies
      run: make dep

    - name: Build viam-csi binary
      run: make build

    - name: Build viam-csi appimage
      run: make package

    - name: Copy binary and appimage to bin folder
      run: make bin

    - name: Run appimage in fresh L4T instance
      run: |
        make image-test TARGET=jetson
        make test-package TARGET=jetson
    
    - name: Run appimage in fresh debian instance
      run: |
        make image-test TARGET=pi
        make test-package TARGET=pi
