name: Test pull request

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  test-package:
    name: Build/Test appimage
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    strategy:
      matrix:
        include:
          - container: ghcr.io/seanavery/viam-cpp-base-jetson:0.0.3
            TARGET: jetson
          - container: ghcr.io/seanavery/viam-cpp-base-pi:0.0.3
            TARGET: pi
    container:
      image: ${{ matrix.container }}
      options: --platform linux/arm64

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set TARGET environment variable
        run: echo "TARGET=${{ matrix.TARGET }}" >> $GITHUB_ENV

      - name: Clean build artifacts
        run: make clean

      - name: Install module dependencies
        run: make dep

      - name: Build viam-csi binary
        run: make build

      - name: Build viam-csi appimage
        run: make package

      - name: Copy binary and appimage to bin folder
        run: make bin

      - name: Run appimage in fresh instance
        run: |
          make image-test
          make test-package
